"""Alembic 空脚本模板"""
# type: skip

"""
add template_type to projects

Revision ID: 24f2c9f525d7
Revises: 0001
Create Date: 2026-06-23 15:59:11.264450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2c9f525d7'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('template_type', sa.String(length=50), server_default='product', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'template_type')
    # ### end Alembic commands ###
